import type { DemoMeta } from "./demos";

/**
 * Demos de texto: todos tienen cajón de entrada y leen `textStore` en cada fotograma.
 * `lib` indica qué librería renderiza; "ambas" combina textmode.js y asciify-engine.
 */
const base = { family: "text" as const, reactive: true };

export const textDemos: DemoMeta[] = [
  {
    ...base,
    slug: "tx-wave",
    lib: "textmode.js",
    render: "textmode",
    title: "Onda de texto",
    blurb: "Letras enormes que ondulan y se apartan del puntero.",
    hint: "Escribe abajo · el puntero aparta las letras · pulsa para empujar más fuerte",
    accent: "#a78bfa",
  },
  {
    ...base,
    slug: "tx-particles",
    lib: "textmode.js",
    render: "textmode",
    title: "Partículas",
    blurb: "Miles de partículas con muelle que componen tu texto.",
    hint: "Escribe abajo y vuelan a su sitio · el puntero las dispersa · pulsa para hacerlas explotar",
    accent: "#38bdf8",
  },
  {
    ...base,
    slug: "tx-glitch",
    lib: "textmode.js",
    render: "textmode",
    title: "Glitch",
    blurb: "Bandas desplazadas, separación cromática y ruido.",
    hint: "El puntero corrompe las letras que toca · pulsa para desatar el glitch",
    accent: "#f472b6",
  },
  {
    ...base,
    slug: "tx-rain",
    lib: "textmode.js",
    render: "textmode",
    title: "Lluvia con texto",
    blurb: "Lluvia digital que se enciende donde hay letras, usando las tuyas.",
    hint: "El puntero deja un rastro de luz · pulsa para ampliarlo",
    accent: "#4ade80",
  },
  {
    ...base,
    slug: "tx-marquee",
    lib: "textmode.js",
    render: "textmode",
    title: "Marquesinas",
    blurb: "Filas de texto con t.print() que corren en sentidos alternos.",
    hint: "Pasa el puntero por una fila para iluminarla",
    accent: "#fbbf24",
  },
  {
    ...base,
    slug: "tx-tile",
    lib: "asciify",
    render: "asciify",
    controls: ["effect"],
    title: "Mosaico de texto",
    blurb: "Tu texto repetido por toda la pantalla, con los 9 efectos de hover del motor.",
    hint: "Elige un efecto en el selector y mueve el puntero por encima",
    accent: "#d4ff00",
  },
  {
    ...base,
    slug: "tx-figlet",
    lib: "asciify",
    render: "asciify",
    controls: ["font"],
    title: "FIGlet",
    blurb: "21 fuentes FIGlet más la bitmap 7×7, convertidas a ASCII con hover de agua.",
    hint: "Cambia la fuente en el selector · el puntero ondula el agua",
    accent: "#8be9fd",
  },
  {
    ...base,
    slug: "tx-bricks",
    lib: "asciify",
    render: "asciify",
    title: "Texto Lego",
    blurb: "Letras de degradado reconstruidas con ladrillos.",
    hint: "El puntero deshace y reordena los ladrillos",
    accent: "#fb923c",
  },
  {
    ...base,
    slug: "tx-dither",
    lib: "asciify",
    render: "asciify",
    title: "Texto en dither",
    blurb: "Letras con halo tramadas en ámbar con patrón que deriva.",
    hint: "Escribe abajo · el texto ondula con el puntero",
    accent: "#f59e0b",
  },
  {
    ...base,
    slug: "tx-braille",
    lib: "asciify",
    render: "asciify",
    title: "Texto braille",
    blurb: "Letras luminosas dibujadas con puntos braille y bloom.",
    hint: "El puntero crea un vórtice sobre los puntos",
    accent: "#9fe8ff",
  },
  {
    ...base,
    slug: "tx-combo-figlet",
    lib: "ambas",
    render: "textmode",
    controls: ["font"],
    title: "FIGlet animado",
    blurb: "asciify-engine genera el arte de texto y textmode.js lo anima carácter a carácter.",
    hint: "Cambia la fuente · el puntero empuja las letras · pulsa para lanzar una onda",
    accent: "#c084fc",
  },
  {
    ...base,
    slug: "tx-combo-layers",
    lib: "ambas",
    render: "layers",
    title: "Capas combinadas",
    blurb: "Olas de puntos de asciify-engine con partículas de texto de textmode.js encima.",
    hint: "El puntero dispersa las partículas · pulsa para explotarlas",
    accent: "#5eead4",
  },
  {
    ...base,
    slug: "tx-scramble",
    lib: "textmode.js",
    render: "textmode",
    title: "Decodificado",
    blurb: "El texto se descifra de izquierda a derecha entre glifos aleatorios, en bucle.",
    hint: "Escribe abajo · el puntero vuelve a mezclar las letras que toca",
    accent: "#34d399",
  },
  {
    ...base,
    slug: "tx-3d",
    lib: "textmode.js",
    render: "textmode",
    title: "Texto 3D",
    blurb: "Tu texto extruido como nube de puntos en 3D que gira con perspectiva.",
    hint: "El puntero inclina el texto · mantén pulsado para girarlo más rápido",
    accent: "#60a5fa",
  },
  {
    ...base,
    slug: "tx-neon",
    lib: "asciify",
    render: "asciify",
    title: "Letrero neón",
    blurb: "Letras de neón rosa con bloom, glitch y grano de CRT.",
    hint: "El puntero deja una estela luminosa · escribe abajo para cambiar el letrero",
    accent: "#ff5ad1",
  },
];
