import type { DemoMeta, Landing } from "./demos";

/**
 * Demos con scroll: la página mide 300vh y el progreso (medido con GSAP ScrollTrigger)
 * mueve el fondo. Encima se superpone una landing de ejemplo cuyo texto entra con GSAP.
 * El copy es de relleno; cámbialo por el de tu producto.
 */
const base = { family: "scroll" as const, reactive: true };

const features = (a: [string, string], b: [string, string], c: [string, string]): [string, string][] => [a, b, c];

const nova = (over: Partial<Landing> = {}): Landing => ({
  kicker: "NOVA · estudio de producto",
  title: "Diseño con carácter",
  sub: "Interfaces que se sienten vivas. Desplaza para ver cómo reacciona el fondo.",
  cta: "Empezar ahora",
  features: features(
    ["Rápido", "Render en GPU y sin dependencias pesadas."],
    ["Expresivo", "Tipografía y movimiento como identidad."],
    ["Accesible", "Respeta preferencias de movimiento reducido."],
  ),
  final: "Listo para lanzar tu próxima landing",
  ...over,
});

export const scrollDemos: DemoMeta[] = [
  {
    ...base,
    slug: "sc-zoom",
    lib: "textmode.js",
    render: "textmode",
    text: true,
    title: "Zoom tipográfico",
    blurb: "Al bajar te sumerges dentro de las letras, hasta 70 aumentos.",
    hint: "Desplaza para entrar en el texto · escribe abajo para cambiarlo",
    accent: "#38bdf8",
    landing: nova({ kicker: "TIPOGRAFÍA", sub: "Cada letra es un mundo. Sigue bajando y entra en él." }),
  },
  {
    ...base,
    slug: "sc-assemble",
    lib: "textmode.js",
    render: "textmode",
    text: true,
    title: "Ensamblaje",
    blurb: "Partículas dispersas que se agrupan en tu texto y estallan al final.",
    hint: "Desplaza para ensamblar y explotar · el puntero aparta las partículas",
    accent: "#a78bfa",
    landing: nova({ kicker: "TITULAR ANIMADO", sub: "Del caos al mensaje, sin una sola imagen." }),
  },
  {
    ...base,
    slug: "sc-rain",
    lib: "textmode.js",
    render: "textmode",
    text: true,
    title: "Lluvia que responde",
    blurb: "La lluvia acelera con tu scroll y acaba solidificándose en tu texto.",
    hint: "Desplaza rápido para acelerar · sube para invertirla · el puntero deja luz",
    accent: "#4ade80",
    landing: nova({ kicker: "CIBERSEGURIDAD", sub: "Datos en movimiento hasta que aparece la señal." }),
  },
  {
    ...base,
    slug: "sc-parallax",
    lib: "textmode.js",
    render: "textmode",
    title: "Ascenso con paralaje",
    blurb: "Del valle al espacio con capas de montañas a distinta velocidad.",
    hint: "Desplaza para subir · el puntero desplaza ligeramente las capas",
    accent: "#f472b6",
    landing: nova({ kicker: "EXPEDICIONES", sub: "Cada capa avanza a su ritmo. Cada scroll es una cota más." }),
  },
  {
    ...base,
    slug: "sc-terminal",
    lib: "textmode.js",
    render: "textmode",
    text: true,
    title: "Terminal que se escribe",
    blurb: "Una terminal que teclea sola según avanzas, con tu texto como nombre de proyecto.",
    hint: "Desplaza para escribir · el texto de abajo es el nombre del proyecto",
    accent: "#22d3ee",
    landing: nova({ kicker: "HERRAMIENTAS PARA DEVS", sub: "Del comando a producción en un solo scroll." }),
  },
  {
    ...base,
    slug: "sc-stats",
    lib: "ambas",
    render: "textmode",
    text: true,
    title: "Cifras que cuentan",
    blurb: "asciify-engine genera los números bitmap y textmode.js los dibuja contando hacia arriba.",
    hint: "Desplaza para ver contar cada cifra · el texto de abajo es el título",
    accent: "#fbbf24",
    landing: nova({ kicker: "RESULTADOS", sub: "Números grandes que se ganan la atención." }),
  },
  {
    ...base,
    slug: "sc-resolution",
    lib: "asciify",
    render: "asciify",
    title: "Resolución progresiva",
    blurb: "La imagen se afina al bajar: de bloques enormes a caracteres finos y, al final, imagen limpia.",
    hint: "Desplaza para enfocar la imagen · el número de la esquina es el tamaño de celda",
    accent: "#f0abfc",
    landing: nova({ kicker: "FOTOGRAFÍA", sub: "Del ruido a la nitidez, píxel a píxel." }),
  },
  {
    ...base,
    slug: "sc-morph",
    lib: "asciify",
    render: "asciify",
    title: "Cambio de estilo",
    blurb: "Cada tramo del scroll cambia el estilo de render: ascii, braille, puntos, Lego, voxel…",
    hint: "Desplaza para recorrer los 9 estilos · la etiqueta de la esquina dice cuál es",
    accent: "#fb923c",
    landing: nova({ kicker: "PORTAFOLIO", sub: "Una misma imagen, nueve formas de contarla." }),
  },
  {
    ...base,
    slug: "sc-elastic",
    lib: "asciify",
    render: "asciify",
    text: true,
    title: "Texto elástico",
    blurb: "El texto se estira y deja estelas según la velocidad del scroll.",
    hint: "Desplaza rápido y frena de golpe · escribe abajo para cambiar el texto",
    accent: "#fb7185",
    landing: nova({ kicker: "MOVIMIENTO", sub: "La velocidad se ve. Prueba a frenar de golpe." }),
  },
  {
    ...base,
    slug: "sc-combo",
    lib: "ambas",
    render: "layers",
    text: true,
    title: "Héroe en capas",
    blurb: "Imagen de asciify-engine que se afina y cambia de estilo, con un titular de textmode.js que se ensambla encima.",
    hint: "Desplaza para afinar la imagen y ensamblar el titular",
    accent: "#5eead4",
    landing: nova({ kicker: "LANDING COMPLETA", sub: "Dos librerías, una sola capa de impacto." }),
  },
];
